# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: TikTok Trending Data Scraper and Archive

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  cron:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    defaults:
      run:
        shell: bash
        working-directory: src

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --if-present
    - run: npm start
    - name: Commit and push if it changed
      run: |-
        git config user.name "GitHub Actions"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date '+%F %H:%M:%S %Z')
        git commit -m "Latest data from ${timestamp}" || exit 0
        git push
